# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2_main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        MainWindow.setMinimumSize(QtCore.QSize(800, 800))
        MainWindow.setMaximumSize(QtCore.QSize(800, 800))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color:rgb(36, 159, 156)")
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.level_main_menu = QtWidgets.QLabel(self.centralwidget)
        self.level_main_menu.setGeometry(QtCore.QRect(550, 20, 210, 111))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.level_main_menu.setFont(font)
        self.level_main_menu.setStyleSheet("background-color: rgb(3, 122, 118);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width:2px;\n"
"border-radius:10px;")
        self.level_main_menu.setObjectName("level_main_menu")
        self.user_main_menu = QtWidgets.QLabel(self.centralwidget)
        self.user_main_menu.setGeometry(QtCore.QRect(40, 20, 460, 111))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.user_main_menu.setFont(font)
        self.user_main_menu.setStyleSheet("background-color: rgb(3, 122, 118);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width:2px;\n"
"border-radius:10px;")
        self.user_main_menu.setAlignment(QtCore.Qt.AlignCenter)
        self.user_main_menu.setObjectName("user_main_menu")
        self.play_button_main_menu = QtWidgets.QPushButton(self.centralwidget)
        self.play_button_main_menu.setGeometry(QtCore.QRect(290, 220, 291, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.play_button_main_menu.setFont(font)
        self.play_button_main_menu.setStyleSheet("QPushButton {\n"
"background-color: rgb(237, 27, 123);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"color: #f44786;\n"
"border-color: #f44786;\n"
"border-width:3px;\n"
"}")
        self.play_button_main_menu.setObjectName("play_button_main_menu")
        self.quit_button_main_menu = QtWidgets.QPushButton(self.centralwidget)
        self.quit_button_main_menu.setGeometry(QtCore.QRect(290, 440, 291, 171))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.quit_button_main_menu.setFont(font)
        self.quit_button_main_menu.setStyleSheet("QPushButton {\n"
"background-color: rgb(237, 27, 123);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"color: #f44786;\n"
"border-color: #f44786;\n"
"border-width:3px;\n"
"}")
        self.quit_button_main_menu.setObjectName("quit_button_main_menu")
        self.progress_main_menu = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_main_menu.setGeometry(QtCore.QRect(60, 200, 81, 511))
        self.progress_main_menu.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.progress_main_menu.setFont(font)
        self.progress_main_menu.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color: rgb(3, 122, 118);\n"
"color: #037a76;")
        self.progress_main_menu.setProperty("value", 10)
        self.progress_main_menu.setAlignment(QtCore.Qt.AlignCenter)
        self.progress_main_menu.setTextVisible(True)
        self.progress_main_menu.setOrientation(QtCore.Qt.Vertical)
        self.progress_main_menu.setInvertedAppearance(False)
        self.progress_main_menu.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progress_main_menu.setObjectName("progress_main_menu")
        self.set_timer_main_menu = QtWidgets.QLabel(self.centralwidget)
        self.set_timer_main_menu.setGeometry(QtCore.QRect(460, 690, 300, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.set_timer_main_menu.setFont(font)
        self.set_timer_main_menu.setStyleSheet("background-color: rgb(3, 122, 118);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width:2px;\n"
"border-radius:10px;")
        self.set_timer_main_menu.setObjectName("set_timer_main_menu")
        self.time_button_main_menu = QtWidgets.QPushButton(self.centralwidget)
        self.time_button_main_menu.setGeometry(QtCore.QRect(680, 695, 50, 50))
        self.time_button_main_menu.setMinimumSize(QtCore.QSize(0, 0))
        self.time_button_main_menu.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.time_button_main_menu.setFont(font)
        self.time_button_main_menu.setStyleSheet("\n"
"QPushButton {\n"
"background-color: rgb(237, 27, 118);\n"
"border-radius:18px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"color: #f44786;\n"
"border-color: #f44786;\n"
"border-width:3px;\n"
"}")
        self.time_button_main_menu.setObjectName("time_button_main_menu")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.level_main_menu.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" vertical-align:super;\">asdafadfadf</span></p></body></html>"))
        self.level_main_menu.setText(_translate("MainWindow", "LEVEL 1"))
        self.user_main_menu.setText(_translate("MainWindow", "WELCOME USER"))
        self.play_button_main_menu.setText(_translate("MainWindow", "PLAY"))
        self.quit_button_main_menu.setText(_translate("MainWindow", "QUIT"))
        self.set_timer_main_menu.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" vertical-align:super;\">asdafadfadf</span></p></body></html>"))
        self.set_timer_main_menu.setText(_translate("MainWindow", "SET TIMER"))
        self.time_button_main_menu.setText(_translate("MainWindow", "time"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
