# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 800)
        MainWindow.setMinimumSize(QtCore.QSize(800, 800))
        MainWindow.setMaximumSize(QtCore.QSize(800, 800))
        font = QtGui.QFont()
        font.setPointSize(17)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(41, 159, 156);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.total_time_game_screen = QtWidgets.QLabel(self.centralwidget)
        self.total_time_game_screen.setGeometry(QtCore.QRect(60, 50, 150, 50))
        self.total_time_game_screen.setMinimumSize(QtCore.QSize(150, 50))
        self.total_time_game_screen.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.total_time_game_screen.setFont(font)
        self.total_time_game_screen.setStyleSheet("background-color: rgb(3, 122, 118);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width:2px;\n"
"border-radius:10px;")
        self.total_time_game_screen.setAlignment(QtCore.Qt.AlignCenter)
        self.total_time_game_screen.setObjectName("total_time_game_screen")
        self.level_game_screen = QtWidgets.QLabel(self.centralwidget)
        self.level_game_screen.setGeometry(QtCore.QRect(590, 50, 150, 50))
        self.level_game_screen.setMinimumSize(QtCore.QSize(150, 50))
        self.level_game_screen.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.level_game_screen.setFont(font)
        self.level_game_screen.setStyleSheet("background-color: rgb(3, 122, 118);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width:2px;\n"
"border-radius:10px;")
        self.level_game_screen.setAlignment(QtCore.Qt.AlignCenter)
        self.level_game_screen.setObjectName("level_game_screen")
        self.level_2 = QtWidgets.QLabel(self.centralwidget)
        self.level_2.setGeometry(QtCore.QRect(320, 70, 150, 90))
        self.level_2.setMinimumSize(QtCore.QSize(150, 90))
        self.level_2.setMaximumSize(QtCore.QSize(150, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.level_2.setFont(font)
        self.level_2.setStyleSheet("background-color: white;\n"
"color: #037a76;\n"
"border-color: #037a76;\n"
"border-style: solid;\n"
"border-width:2px;\n"
"border-radius:10px;")
        self.level_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.level_2.setObjectName("level_2")
        self.flash_card_game_screen = QtWidgets.QLabel(self.centralwidget)
        self.flash_card_game_screen.setGeometry(QtCore.QRect(250, 200, 300, 300))
        self.flash_card_game_screen.setMinimumSize(QtCore.QSize(300, 300))
        self.flash_card_game_screen.setMaximumSize(QtCore.QSize(300, 300))
        self.flash_card_game_screen.setStyleSheet("border-color: #037a76;\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width:2px;\n"
"border-radius:25px;")
        self.flash_card_game_screen.setText("")
        self.flash_card_game_screen.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.flash_card_game_screen.setObjectName("flash_card_game_screen")
        self.progress_game_screen = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_game_screen.setGeometry(QtCore.QRect(190, 690, 420, 50))
        self.progress_game_screen.setMinimumSize(QtCore.QSize(420, 50))
        self.progress_game_screen.setMaximumSize(QtCore.QSize(420, 50))
        self.progress_game_screen.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: #037a76;\n"
"border-color: #037a76;\n"
"border-style: solid;\n"
"border-width:2px;\n"
"border-radius:10px;")
        self.progress_game_screen.setProperty("value", 24)
        self.progress_game_screen.setAlignment(QtCore.Qt.AlignCenter)
        self.progress_game_screen.setObjectName("progress_game_screen")
        self.false_game_screen = QtWidgets.QLabel(self.centralwidget)
        self.false_game_screen.setGeometry(QtCore.QRect(60, 260, 100, 150))
        self.false_game_screen.setMinimumSize(QtCore.QSize(100, 150))
        self.false_game_screen.setMaximumSize(QtCore.QSize(100, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.false_game_screen.setFont(font)
        self.false_game_screen.setStyleSheet("border-color: white;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(237,27,118);\n"
"border-style: solid;\n"
"border-width:2px;\n"
"border-radius:10px;")
        self.false_game_screen.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.false_game_screen.setObjectName("false_game_screen")
        self.true_game_screen = QtWidgets.QLabel(self.centralwidget)
        self.true_game_screen.setGeometry(QtCore.QRect(640, 260, 100, 150))
        self.true_game_screen.setMinimumSize(QtCore.QSize(100, 150))
        self.true_game_screen.setMaximumSize(QtCore.QSize(100, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.true_game_screen.setFont(font)
        self.true_game_screen.setStyleSheet("background-color: rgb(3, 122, 118);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width:2px;\n"
"border-radius:10px;")
        self.true_game_screen.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.true_game_screen.setObjectName("true_game_screen")
        self.num_of_true_game_screen = QtWidgets.QLabel(self.centralwidget)
        self.num_of_true_game_screen.setGeometry(QtCore.QRect(665, 320, 50, 50))
        self.num_of_true_game_screen.setMinimumSize(QtCore.QSize(50, 50))
        self.num_of_true_game_screen.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.num_of_true_game_screen.setFont(font)
        self.num_of_true_game_screen.setStyleSheet("border-radius:25px;\n"
"color: rgb(3, 122, 118);\n"
"background-color: rgb(255, 255, 255);")
        self.num_of_true_game_screen.setAlignment(QtCore.Qt.AlignCenter)
        self.num_of_true_game_screen.setObjectName("num_of_true_game_screen")
        self.num_of_false_game_screen = QtWidgets.QLabel(self.centralwidget)
        self.num_of_false_game_screen.setGeometry(QtCore.QRect(85, 320, 50, 50))
        self.num_of_false_game_screen.setMinimumSize(QtCore.QSize(50, 50))
        self.num_of_false_game_screen.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.num_of_false_game_screen.setFont(font)
        self.num_of_false_game_screen.setStyleSheet("border-radius:25px;\n"
"color: rgb(237,27,118);\n"
"background-color: rgb(255,255,255);")
        self.num_of_false_game_screen.setAlignment(QtCore.Qt.AlignCenter)
        self.num_of_false_game_screen.setObjectName("num_of_false_game_screen")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(370, 100, 50, 50))
        self.label_5.setMinimumSize(QtCore.QSize(50, 50))
        self.label_5.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border-radius:25px;\n"
"color: rgb(3, 122, 118);\n"
"background-color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.language_flash_card_game_screen = QtWidgets.QLabel(self.centralwidget)
        self.language_flash_card_game_screen.setGeometry(QtCore.QRect(270, 240, 260, 50))
        self.language_flash_card_game_screen.setMinimumSize(QtCore.QSize(260, 50))
        self.language_flash_card_game_screen.setMaximumSize(QtCore.QSize(260, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.language_flash_card_game_screen.setFont(font)
        self.language_flash_card_game_screen.setStyleSheet("border-radius:10px;\n"
"color: rgb(3, 122, 118);\n"
"background-color: rgb(255, 255, 255);")
        self.language_flash_card_game_screen.setAlignment(QtCore.Qt.AlignCenter)
        self.language_flash_card_game_screen.setObjectName("language_flash_card_game_screen")
        self.language_flash_card_game_screen_2 = QtWidgets.QLabel(self.centralwidget)
        self.language_flash_card_game_screen_2.setGeometry(QtCore.QRect(270, 390, 260, 50))
        self.language_flash_card_game_screen_2.setMinimumSize(QtCore.QSize(260, 50))
        self.language_flash_card_game_screen_2.setMaximumSize(QtCore.QSize(260, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.language_flash_card_game_screen_2.setFont(font)
        self.language_flash_card_game_screen_2.setStyleSheet("border-radius:10px;\n"
"color: rgb(3, 122, 118);\n"
"background-color: rgb(255, 255, 255);")
        self.language_flash_card_game_screen_2.setAlignment(QtCore.Qt.AlignCenter)
        self.language_flash_card_game_screen_2.setObjectName("language_flash_card_game_screen_2")
        self.exit_login_page = QtWidgets.QPushButton(self.centralwidget)
        self.exit_login_page.setGeometry(QtCore.QRect(640, 690, 100, 50))
        self.exit_login_page.setMinimumSize(QtCore.QSize(100, 50))
        self.exit_login_page.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.exit_login_page.setFont(font)
        self.exit_login_page.setStyleSheet("QPushButton{\n"
"background-color: rgb(237, 27, 118);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"color: #f44786;\n"
"border-color: #f44786;\n"
"border-width:3px;\n"
"}")
        self.exit_login_page.setObjectName("exit_login_page")
        self.back_login_page = QtWidgets.QPushButton(self.centralwidget)
        self.back_login_page.setGeometry(QtCore.QRect(60, 690, 100, 50))
        self.back_login_page.setMinimumSize(QtCore.QSize(100, 50))
        self.back_login_page.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.back_login_page.setFont(font)
        self.back_login_page.setStyleSheet("QPushButton{\n"
"background-color: rgb(237, 27, 118);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"color: #f44786;\n"
"border-color: #f44786;\n"
"border-width:3px;\n"
"}")
        self.back_login_page.setObjectName("back_login_page")
        self.false_button_game_screen = QtWidgets.QPushButton(self.centralwidget)
        self.false_button_game_screen.setGeometry(QtCore.QRect(260, 530, 100, 100))
        self.false_button_game_screen.setMinimumSize(QtCore.QSize(100, 100))
        self.false_button_game_screen.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.false_button_game_screen.setFont(font)
        self.false_button_game_screen.setStyleSheet("QPushButton{\n"
"background-color: rgb(237, 27, 118);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width:3px;\n"
"border-radius:50px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"color: #f44786;\n"
"border-color: #f44786;\n"
"border-width:3px;\n"
"}")
        self.false_button_game_screen.setObjectName("false_button_game_screen")
        self.true_button_game_screen = QtWidgets.QPushButton(self.centralwidget)
        self.true_button_game_screen.setGeometry(QtCore.QRect(470, 530, 100, 100))
        self.true_button_game_screen.setMinimumSize(QtCore.QSize(100, 100))
        self.true_button_game_screen.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.true_button_game_screen.setFont(font)
        self.true_button_game_screen.setStyleSheet("QPushButton{\n"
"border-radius:50px;\n"
"background-color: #037a76;\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width:4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"color: #037a76;;\n"
"border-color: #037a76;\n"
"border-width:3px;\n"
"}")
        self.true_button_game_screen.setObjectName("true_button_game_screen")
        self.level_2.raise_()
        self.label_5.raise_()
        self.total_time_game_screen.raise_()
        self.level_game_screen.raise_()
        self.flash_card_game_screen.raise_()
        self.progress_game_screen.raise_()
        self.false_game_screen.raise_()
        self.true_game_screen.raise_()
        self.num_of_true_game_screen.raise_()
        self.num_of_false_game_screen.raise_()
        self.language_flash_card_game_screen.raise_()
        self.language_flash_card_game_screen_2.raise_()
        self.exit_login_page.raise_()
        self.back_login_page.raise_()
        self.false_button_game_screen.raise_()
        self.true_button_game_screen.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.total_time_game_screen.setText(_translate("MainWindow", "TOTAL TIME"))
        self.level_game_screen.setText(_translate("MainWindow", "LEVEL"))
        self.level_2.setText(_translate("MainWindow", "TIME"))
        self.false_game_screen.setText(_translate("MainWindow", "FALSE"))
        self.true_game_screen.setText(_translate("MainWindow", "TRUE"))
        self.num_of_true_game_screen.setText(_translate("MainWindow", "2"))
        self.num_of_false_game_screen.setText(_translate("MainWindow", "2"))
        self.label_5.setText(_translate("MainWindow", "3"))
        self.language_flash_card_game_screen.setText(_translate("MainWindow", "Netherlands"))
        self.language_flash_card_game_screen_2.setText(_translate("MainWindow", "je"))
        self.exit_login_page.setText(_translate("MainWindow", "EXIT"))
        self.back_login_page.setText(_translate("MainWindow", "BACK"))
        self.false_button_game_screen.setText(_translate("MainWindow", "X"))
        self.true_button_game_screen.setText(_translate("MainWindow", "✓"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
